global:
  scrape_interval:     1s   # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1s    # # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  # using pull
  - job_name: "node_exporter"
    http_sd_configs:
      - url: http://10.74.152.184:8080/hosts  # k8s not support cause idc could not ping docker ip.

############

global:
  scrape_interval:     1s   # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1s    # # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "pushgateway"  #这个名称可以自定义，后面会用到
    static_configs:
      - targets: ["10.14.141.25:8080"]