version: '3'
services:
  rabbitmq1:
    image: rabbitmq:3.7-management
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
#      restart_policy:
#        condition: any
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: rabbitmq1
    container_name: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
    volumes:
      - /Users/huaxinrui/docker/rabbitmq-cluster/data/rabbitmq1:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime


  rabbitmq2:
    image: rabbitmq:3.7-management
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
#      restart_policy:
#        condition: any
    ports:
      - "5673:5672"
    hostname: rabbitmq2
    container_name: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
    volumes:
      - /Users/huaxinrui/docker/rabbitmq-cluster/data/rabbitmq2:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime


  rabbitmq3:
    image: rabbitmq:3.7-management
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
#      restart_policy:
#        condition: any
    ports:
      - "5674:5672"
    hostname: rabbitmq3
    container_name: rabbitmq3
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
    volumes:
      - /Users/huaxinrui/docker/rabbitmq-cluster/data/rabbitmq3:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime