// Code generated by protoc-gen-go. DO NOT EDIT.
// source: component/service/proto/tmp/tmp.proto

package test

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestReq struct {
	Payload              string   `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestReq) Reset()         { *m = TestReq{} }
func (m *TestReq) String() string { return proto.CompactTextString(m) }
func (*TestReq) ProtoMessage()    {}
func (*TestReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a68dd0c45c9ff39, []int{0}
}

func (m *TestReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestReq.Unmarshal(m, b)
}
func (m *TestReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestReq.Marshal(b, m, deterministic)
}
func (m *TestReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestReq.Merge(m, src)
}
func (m *TestReq) XXX_Size() int {
	return xxx_messageInfo_TestReq.Size(m)
}
func (m *TestReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TestReq.DiscardUnknown(m)
}

var xxx_messageInfo_TestReq proto.InternalMessageInfo

func (m *TestReq) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type TestResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestResponse) Reset()         { *m = TestResponse{} }
func (m *TestResponse) String() string { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()    {}
func (*TestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a68dd0c45c9ff39, []int{1}
}

func (m *TestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResponse.Unmarshal(m, b)
}
func (m *TestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResponse.Marshal(b, m, deterministic)
}
func (m *TestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResponse.Merge(m, src)
}
func (m *TestResponse) XXX_Size() int {
	return xxx_messageInfo_TestResponse.Size(m)
}
func (m *TestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestResponse proto.InternalMessageInfo

func (m *TestResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*TestReq)(nil), "service.TestReq")
	proto.RegisterType((*TestResponse)(nil), "service.TestResponse")
}

func init() {
	proto.RegisterFile("component/service/proto/tmp/tmp.proto", fileDescriptor_5a68dd0c45c9ff39)
}

var fileDescriptor_5a68dd0c45c9ff39 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4f, 0xce, 0xcf, 0x2d,
	0xc8, 0xcf, 0x4b, 0xcd, 0x2b, 0xd1, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2f, 0x28,
	0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x49, 0x2d, 0x2e, 0x01, 0x13, 0x7a, 0x60, 0xbe, 0x10, 0x3b, 0x54,
	0x5a, 0x49, 0x99, 0x8b, 0x3d, 0x24, 0xb5, 0xb8, 0x24, 0x28, 0xb5, 0x50, 0x48, 0x82, 0x8b, 0x3d,
	0x20, 0xb1, 0x32, 0x27, 0x3f, 0x31, 0x45, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc6, 0x55,
	0x52, 0xe2, 0xe2, 0x81, 0x28, 0x2a, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe2, 0x62, 0x71,
	0x49, 0x2c, 0x49, 0x94, 0x60, 0x04, 0x2b, 0x03, 0xb3, 0x8d, 0x6c, 0xa0, 0x06, 0x15, 0x24, 0x0b,
	0x19, 0x72, 0xb1, 0x80, 0x98, 0x42, 0x02, 0x7a, 0x50, 0x5b, 0xf4, 0xa0, 0x56, 0x48, 0x89, 0xa2,
	0x89, 0x40, 0xcc, 0x53, 0x62, 0x70, 0xe2, 0x8e, 0xe2, 0xd4, 0xb3, 0x86, 0xca, 0x25, 0xb1, 0x81,
	0xdd, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x73, 0xf1, 0x6c, 0xce, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestRpcClient is the client API for TestRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestRpcClient interface {
	Test(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*TestResponse, error)
}

type testRpcClient struct {
	cc *grpc.ClientConn
}

func NewTestRpcClient(cc *grpc.ClientConn) TestRpcClient {
	return &testRpcClient{cc}
}

func (c *testRpcClient) Test(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, "/service.TestRpc/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestRpcServer is the server API for TestRpc service.
type TestRpcServer interface {
	Test(context.Context, *TestReq) (*TestResponse, error)
}

// UnimplementedTestRpcServer can be embedded to have forward compatible implementations.
type UnimplementedTestRpcServer struct {
}

func (*UnimplementedTestRpcServer) Test(ctx context.Context, req *TestReq) (*TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}

func RegisterTestRpcServer(s *grpc.Server, srv TestRpcServer) {
	s.RegisterService(&_TestRpc_serviceDesc, srv)
}

func _TestRpc_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestRpcServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.TestRpc/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestRpcServer).Test(ctx, req.(*TestReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.TestRpc",
	HandlerType: (*TestRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _TestRpc_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "component/service/proto/tmp/tmp.proto",
}
