// Code generated by protoc-gen-go. DO NOT EDIT.
// source: component/service/proto/flow.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TriggerReq struct {
	Srv                  string   `protobuf:"bytes,1,opt,name=Srv,proto3" json:"Srv,omitempty"`
	Mod                  uint32   `protobuf:"varint,2,opt,name=Mod,proto3" json:"Mod,omitempty"`
	AppName              string   `protobuf:"bytes,3,opt,name=AppName,proto3" json:"AppName,omitempty"`
	PlaybookId           int32    `protobuf:"varint,4,opt,name=PlaybookId,proto3" json:"PlaybookId,omitempty"`
	AppToken             string   `protobuf:"bytes,5,opt,name=AppToken,proto3" json:"AppToken,omitempty"`
	Sync                 bool     `protobuf:"varint,6,opt,name=Sync,proto3" json:"Sync,omitempty"`
	Data                 []byte   `protobuf:"bytes,7,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TriggerReq) Reset()         { *m = TriggerReq{} }
func (m *TriggerReq) String() string { return proto.CompactTextString(m) }
func (*TriggerReq) ProtoMessage()    {}
func (*TriggerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{0}
}

func (m *TriggerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerReq.Unmarshal(m, b)
}
func (m *TriggerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerReq.Marshal(b, m, deterministic)
}
func (m *TriggerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerReq.Merge(m, src)
}
func (m *TriggerReq) XXX_Size() int {
	return xxx_messageInfo_TriggerReq.Size(m)
}
func (m *TriggerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerReq.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerReq proto.InternalMessageInfo

func (m *TriggerReq) GetSrv() string {
	if m != nil {
		return m.Srv
	}
	return ""
}

func (m *TriggerReq) GetMod() uint32 {
	if m != nil {
		return m.Mod
	}
	return 0
}

func (m *TriggerReq) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *TriggerReq) GetPlaybookId() int32 {
	if m != nil {
		return m.PlaybookId
	}
	return 0
}

func (m *TriggerReq) GetAppToken() string {
	if m != nil {
		return m.AppToken
	}
	return ""
}

func (m *TriggerReq) GetSync() bool {
	if m != nil {
		return m.Sync
	}
	return false
}

func (m *TriggerReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type TriggerResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	SyncResult           []byte   `protobuf:"bytes,2,opt,name=SyncResult,proto3" json:"SyncResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TriggerResponse) Reset()         { *m = TriggerResponse{} }
func (m *TriggerResponse) String() string { return proto.CompactTextString(m) }
func (*TriggerResponse) ProtoMessage()    {}
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{1}
}

func (m *TriggerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerResponse.Unmarshal(m, b)
}
func (m *TriggerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerResponse.Marshal(b, m, deterministic)
}
func (m *TriggerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerResponse.Merge(m, src)
}
func (m *TriggerResponse) XXX_Size() int {
	return xxx_messageInfo_TriggerResponse.Size(m)
}
func (m *TriggerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerResponse proto.InternalMessageInfo

func (m *TriggerResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *TriggerResponse) GetSyncResult() []byte {
	if m != nil {
		return m.SyncResult
	}
	return nil
}

type WorkerRespReq struct {
	Srv                  string   `protobuf:"bytes,1,opt,name=Srv,proto3" json:"Srv,omitempty"`
	Mod                  uint32   `protobuf:"varint,2,opt,name=Mod,proto3" json:"Mod,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerRespReq) Reset()         { *m = WorkerRespReq{} }
func (m *WorkerRespReq) String() string { return proto.CompactTextString(m) }
func (*WorkerRespReq) ProtoMessage()    {}
func (*WorkerRespReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{2}
}

func (m *WorkerRespReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerRespReq.Unmarshal(m, b)
}
func (m *WorkerRespReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerRespReq.Marshal(b, m, deterministic)
}
func (m *WorkerRespReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerRespReq.Merge(m, src)
}
func (m *WorkerRespReq) XXX_Size() int {
	return xxx_messageInfo_WorkerRespReq.Size(m)
}
func (m *WorkerRespReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerRespReq.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerRespReq proto.InternalMessageInfo

func (m *WorkerRespReq) GetSrv() string {
	if m != nil {
		return m.Srv
	}
	return ""
}

func (m *WorkerRespReq) GetMod() uint32 {
	if m != nil {
		return m.Mod
	}
	return 0
}

func (m *WorkerRespReq) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type WorkerRespResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerRespResponse) Reset()         { *m = WorkerRespResponse{} }
func (m *WorkerRespResponse) String() string { return proto.CompactTextString(m) }
func (*WorkerRespResponse) ProtoMessage()    {}
func (*WorkerRespResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{3}
}

func (m *WorkerRespResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerRespResponse.Unmarshal(m, b)
}
func (m *WorkerRespResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerRespResponse.Marshal(b, m, deterministic)
}
func (m *WorkerRespResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerRespResponse.Merge(m, src)
}
func (m *WorkerRespResponse) XXX_Size() int {
	return xxx_messageInfo_WorkerRespResponse.Size(m)
}
func (m *WorkerRespResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerRespResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerRespResponse proto.InternalMessageInfo

func (m *WorkerRespResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type WorkerExceptionReq struct {
	Srv                  string   `protobuf:"bytes,1,opt,name=Srv,proto3" json:"Srv,omitempty"`
	Mod                  uint32   `protobuf:"varint,2,opt,name=Mod,proto3" json:"Mod,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerExceptionReq) Reset()         { *m = WorkerExceptionReq{} }
func (m *WorkerExceptionReq) String() string { return proto.CompactTextString(m) }
func (*WorkerExceptionReq) ProtoMessage()    {}
func (*WorkerExceptionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{4}
}

func (m *WorkerExceptionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerExceptionReq.Unmarshal(m, b)
}
func (m *WorkerExceptionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerExceptionReq.Marshal(b, m, deterministic)
}
func (m *WorkerExceptionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerExceptionReq.Merge(m, src)
}
func (m *WorkerExceptionReq) XXX_Size() int {
	return xxx_messageInfo_WorkerExceptionReq.Size(m)
}
func (m *WorkerExceptionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerExceptionReq.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerExceptionReq proto.InternalMessageInfo

func (m *WorkerExceptionReq) GetSrv() string {
	if m != nil {
		return m.Srv
	}
	return ""
}

func (m *WorkerExceptionReq) GetMod() uint32 {
	if m != nil {
		return m.Mod
	}
	return 0
}

func (m *WorkerExceptionReq) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type WorkerExceptionResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerExceptionResponse) Reset()         { *m = WorkerExceptionResponse{} }
func (m *WorkerExceptionResponse) String() string { return proto.CompactTextString(m) }
func (*WorkerExceptionResponse) ProtoMessage()    {}
func (*WorkerExceptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{5}
}

func (m *WorkerExceptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerExceptionResponse.Unmarshal(m, b)
}
func (m *WorkerExceptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerExceptionResponse.Marshal(b, m, deterministic)
}
func (m *WorkerExceptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerExceptionResponse.Merge(m, src)
}
func (m *WorkerExceptionResponse) XXX_Size() int {
	return xxx_messageInfo_WorkerExceptionResponse.Size(m)
}
func (m *WorkerExceptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerExceptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerExceptionResponse proto.InternalMessageInfo

func (m *WorkerExceptionResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type HookReq struct {
	TraceId              uint64   `protobuf:"varint,1,opt,name=TraceId,proto3" json:"TraceId,omitempty"`
	NodeCode             string   `protobuf:"bytes,2,opt,name=NodeCode,proto3" json:"NodeCode,omitempty"`
	SnapshotId           uint32   `protobuf:"varint,3,opt,name=SnapshotId,proto3" json:"SnapshotId,omitempty"`
	Srv                  string   `protobuf:"bytes,4,opt,name=Srv,proto3" json:"Srv,omitempty"`
	Mod                  uint32   `protobuf:"varint,5,opt,name=Mod,proto3" json:"Mod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HookReq) Reset()         { *m = HookReq{} }
func (m *HookReq) String() string { return proto.CompactTextString(m) }
func (*HookReq) ProtoMessage()    {}
func (*HookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{6}
}

func (m *HookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HookReq.Unmarshal(m, b)
}
func (m *HookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HookReq.Marshal(b, m, deterministic)
}
func (m *HookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HookReq.Merge(m, src)
}
func (m *HookReq) XXX_Size() int {
	return xxx_messageInfo_HookReq.Size(m)
}
func (m *HookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HookReq.DiscardUnknown(m)
}

var xxx_messageInfo_HookReq proto.InternalMessageInfo

func (m *HookReq) GetTraceId() uint64 {
	if m != nil {
		return m.TraceId
	}
	return 0
}

func (m *HookReq) GetNodeCode() string {
	if m != nil {
		return m.NodeCode
	}
	return ""
}

func (m *HookReq) GetSnapshotId() uint32 {
	if m != nil {
		return m.SnapshotId
	}
	return 0
}

func (m *HookReq) GetSrv() string {
	if m != nil {
		return m.Srv
	}
	return ""
}

func (m *HookReq) GetMod() uint32 {
	if m != nil {
		return m.Mod
	}
	return 0
}

type HookResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HookResponse) Reset()         { *m = HookResponse{} }
func (m *HookResponse) String() string { return proto.CompactTextString(m) }
func (*HookResponse) ProtoMessage()    {}
func (*HookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{7}
}

func (m *HookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HookResponse.Unmarshal(m, b)
}
func (m *HookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HookResponse.Marshal(b, m, deterministic)
}
func (m *HookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HookResponse.Merge(m, src)
}
func (m *HookResponse) XXX_Size() int {
	return xxx_messageInfo_HookResponse.Size(m)
}
func (m *HookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HookResponse proto.InternalMessageInfo

func (m *HookResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GetPlaybookReq struct {
	Pbid                 int32    `protobuf:"varint,1,opt,name=Pbid,proto3" json:"Pbid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlaybookReq) Reset()         { *m = GetPlaybookReq{} }
func (m *GetPlaybookReq) String() string { return proto.CompactTextString(m) }
func (*GetPlaybookReq) ProtoMessage()    {}
func (*GetPlaybookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{8}
}

func (m *GetPlaybookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlaybookReq.Unmarshal(m, b)
}
func (m *GetPlaybookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlaybookReq.Marshal(b, m, deterministic)
}
func (m *GetPlaybookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlaybookReq.Merge(m, src)
}
func (m *GetPlaybookReq) XXX_Size() int {
	return xxx_messageInfo_GetPlaybookReq.Size(m)
}
func (m *GetPlaybookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlaybookReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlaybookReq proto.InternalMessageInfo

func (m *GetPlaybookReq) GetPbid() int32 {
	if m != nil {
		return m.Pbid
	}
	return 0
}

type GetPlaybookResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlaybookResponse) Reset()         { *m = GetPlaybookResponse{} }
func (m *GetPlaybookResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlaybookResponse) ProtoMessage()    {}
func (*GetPlaybookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{9}
}

func (m *GetPlaybookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlaybookResponse.Unmarshal(m, b)
}
func (m *GetPlaybookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlaybookResponse.Marshal(b, m, deterministic)
}
func (m *GetPlaybookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlaybookResponse.Merge(m, src)
}
func (m *GetPlaybookResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlaybookResponse.Size(m)
}
func (m *GetPlaybookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlaybookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlaybookResponse proto.InternalMessageInfo

func (m *GetPlaybookResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SwitchVersionReq struct {
	PlayBookId           int32    `protobuf:"varint,1,opt,name=PlayBookId,proto3" json:"PlayBookId,omitempty"`
	SnapShotId           int32    `protobuf:"varint,2,opt,name=SnapShotId,proto3" json:"SnapShotId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchVersionReq) Reset()         { *m = SwitchVersionReq{} }
func (m *SwitchVersionReq) String() string { return proto.CompactTextString(m) }
func (*SwitchVersionReq) ProtoMessage()    {}
func (*SwitchVersionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{10}
}

func (m *SwitchVersionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchVersionReq.Unmarshal(m, b)
}
func (m *SwitchVersionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchVersionReq.Marshal(b, m, deterministic)
}
func (m *SwitchVersionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchVersionReq.Merge(m, src)
}
func (m *SwitchVersionReq) XXX_Size() int {
	return xxx_messageInfo_SwitchVersionReq.Size(m)
}
func (m *SwitchVersionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchVersionReq.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchVersionReq proto.InternalMessageInfo

func (m *SwitchVersionReq) GetPlayBookId() int32 {
	if m != nil {
		return m.PlayBookId
	}
	return 0
}

func (m *SwitchVersionReq) GetSnapShotId() int32 {
	if m != nil {
		return m.SnapShotId
	}
	return 0
}

type SwitchVersionResponse struct {
	PlayBookId           int32    `protobuf:"varint,1,opt,name=PlayBookId,proto3" json:"PlayBookId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchVersionResponse) Reset()         { *m = SwitchVersionResponse{} }
func (m *SwitchVersionResponse) String() string { return proto.CompactTextString(m) }
func (*SwitchVersionResponse) ProtoMessage()    {}
func (*SwitchVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{11}
}

func (m *SwitchVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchVersionResponse.Unmarshal(m, b)
}
func (m *SwitchVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchVersionResponse.Marshal(b, m, deterministic)
}
func (m *SwitchVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchVersionResponse.Merge(m, src)
}
func (m *SwitchVersionResponse) XXX_Size() int {
	return xxx_messageInfo_SwitchVersionResponse.Size(m)
}
func (m *SwitchVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchVersionResponse proto.InternalMessageInfo

func (m *SwitchVersionResponse) GetPlayBookId() int32 {
	if m != nil {
		return m.PlayBookId
	}
	return 0
}

type SubmitPlayBookReq struct {
	Body                 []byte   `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitPlayBookReq) Reset()         { *m = SubmitPlayBookReq{} }
func (m *SubmitPlayBookReq) String() string { return proto.CompactTextString(m) }
func (*SubmitPlayBookReq) ProtoMessage()    {}
func (*SubmitPlayBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{12}
}

func (m *SubmitPlayBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitPlayBookReq.Unmarshal(m, b)
}
func (m *SubmitPlayBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitPlayBookReq.Marshal(b, m, deterministic)
}
func (m *SubmitPlayBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitPlayBookReq.Merge(m, src)
}
func (m *SubmitPlayBookReq) XXX_Size() int {
	return xxx_messageInfo_SubmitPlayBookReq.Size(m)
}
func (m *SubmitPlayBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitPlayBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitPlayBookReq proto.InternalMessageInfo

func (m *SubmitPlayBookReq) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type SubmitPlayBookResponse struct {
	PlaybookId           int32    `protobuf:"varint,1,opt,name=PlaybookId,proto3" json:"PlaybookId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitPlayBookResponse) Reset()         { *m = SubmitPlayBookResponse{} }
func (m *SubmitPlayBookResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitPlayBookResponse) ProtoMessage()    {}
func (*SubmitPlayBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{13}
}

func (m *SubmitPlayBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitPlayBookResponse.Unmarshal(m, b)
}
func (m *SubmitPlayBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitPlayBookResponse.Marshal(b, m, deterministic)
}
func (m *SubmitPlayBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitPlayBookResponse.Merge(m, src)
}
func (m *SubmitPlayBookResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitPlayBookResponse.Size(m)
}
func (m *SubmitPlayBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitPlayBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitPlayBookResponse proto.InternalMessageInfo

func (m *SubmitPlayBookResponse) GetPlaybookId() int32 {
	if m != nil {
		return m.PlaybookId
	}
	return 0
}

type UpdateAppInternalReq struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	AppId                int32    `protobuf:"varint,2,opt,name=AppId,proto3" json:"AppId,omitempty"`
	Brokers              string   `protobuf:"bytes,3,opt,name=Brokers,proto3" json:"Brokers,omitempty"`
	Eps                  int32    `protobuf:"varint,4,opt,name=Eps,proto3" json:"Eps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAppInternalReq) Reset()         { *m = UpdateAppInternalReq{} }
func (m *UpdateAppInternalReq) String() string { return proto.CompactTextString(m) }
func (*UpdateAppInternalReq) ProtoMessage()    {}
func (*UpdateAppInternalReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{14}
}

func (m *UpdateAppInternalReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppInternalReq.Unmarshal(m, b)
}
func (m *UpdateAppInternalReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppInternalReq.Marshal(b, m, deterministic)
}
func (m *UpdateAppInternalReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppInternalReq.Merge(m, src)
}
func (m *UpdateAppInternalReq) XXX_Size() int {
	return xxx_messageInfo_UpdateAppInternalReq.Size(m)
}
func (m *UpdateAppInternalReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppInternalReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppInternalReq proto.InternalMessageInfo

func (m *UpdateAppInternalReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateAppInternalReq) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *UpdateAppInternalReq) GetBrokers() string {
	if m != nil {
		return m.Brokers
	}
	return ""
}

func (m *UpdateAppInternalReq) GetEps() int32 {
	if m != nil {
		return m.Eps
	}
	return 0
}

type UpdateAppInternalResponse struct {
	AppId                int32    `protobuf:"varint,1,opt,name=AppId,proto3" json:"AppId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAppInternalResponse) Reset()         { *m = UpdateAppInternalResponse{} }
func (m *UpdateAppInternalResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAppInternalResponse) ProtoMessage()    {}
func (*UpdateAppInternalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{15}
}

func (m *UpdateAppInternalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppInternalResponse.Unmarshal(m, b)
}
func (m *UpdateAppInternalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppInternalResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAppInternalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppInternalResponse.Merge(m, src)
}
func (m *UpdateAppInternalResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAppInternalResponse.Size(m)
}
func (m *UpdateAppInternalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppInternalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppInternalResponse proto.InternalMessageInfo

func (m *UpdateAppInternalResponse) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

type PingReq struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{16}
}

func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (m *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(m, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

func (m *PingReq) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PongResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongResponse) Reset()         { *m = PongResponse{} }
func (m *PongResponse) String() string { return proto.CompactTextString(m) }
func (*PongResponse) ProtoMessage()    {}
func (*PongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{17}
}

func (m *PongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongResponse.Unmarshal(m, b)
}
func (m *PongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongResponse.Marshal(b, m, deterministic)
}
func (m *PongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongResponse.Merge(m, src)
}
func (m *PongResponse) XXX_Size() int {
	return xxx_messageInfo_PongResponse.Size(m)
}
func (m *PongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PongResponse proto.InternalMessageInfo

func (m *PongResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type GetCacheReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCacheReq) Reset()         { *m = GetCacheReq{} }
func (m *GetCacheReq) String() string { return proto.CompactTextString(m) }
func (*GetCacheReq) ProtoMessage()    {}
func (*GetCacheReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{18}
}

func (m *GetCacheReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCacheReq.Unmarshal(m, b)
}
func (m *GetCacheReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCacheReq.Marshal(b, m, deterministic)
}
func (m *GetCacheReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCacheReq.Merge(m, src)
}
func (m *GetCacheReq) XXX_Size() int {
	return xxx_messageInfo_GetCacheReq.Size(m)
}
func (m *GetCacheReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCacheReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCacheReq proto.InternalMessageInfo

type GetCacheResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCacheResponse) Reset()         { *m = GetCacheResponse{} }
func (m *GetCacheResponse) String() string { return proto.CompactTextString(m) }
func (*GetCacheResponse) ProtoMessage()    {}
func (*GetCacheResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{19}
}

func (m *GetCacheResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCacheResponse.Unmarshal(m, b)
}
func (m *GetCacheResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCacheResponse.Marshal(b, m, deterministic)
}
func (m *GetCacheResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCacheResponse.Merge(m, src)
}
func (m *GetCacheResponse) XXX_Size() int {
	return xxx_messageInfo_GetCacheResponse.Size(m)
}
func (m *GetCacheResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCacheResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCacheResponse proto.InternalMessageInfo

func (m *GetCacheResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetAckReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAckReq) Reset()         { *m = GetAckReq{} }
func (m *GetAckReq) String() string { return proto.CompactTextString(m) }
func (*GetAckReq) ProtoMessage()    {}
func (*GetAckReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{20}
}

func (m *GetAckReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAckReq.Unmarshal(m, b)
}
func (m *GetAckReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAckReq.Marshal(b, m, deterministic)
}
func (m *GetAckReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAckReq.Merge(m, src)
}
func (m *GetAckReq) XXX_Size() int {
	return xxx_messageInfo_GetAckReq.Size(m)
}
func (m *GetAckReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAckReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAckReq proto.InternalMessageInfo

type GetAckResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAckResponse) Reset()         { *m = GetAckResponse{} }
func (m *GetAckResponse) String() string { return proto.CompactTextString(m) }
func (*GetAckResponse) ProtoMessage()    {}
func (*GetAckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{21}
}

func (m *GetAckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAckResponse.Unmarshal(m, b)
}
func (m *GetAckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAckResponse.Marshal(b, m, deterministic)
}
func (m *GetAckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAckResponse.Merge(m, src)
}
func (m *GetAckResponse) XXX_Size() int {
	return xxx_messageInfo_GetAckResponse.Size(m)
}
func (m *GetAckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAckResponse proto.InternalMessageInfo

func (m *GetAckResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetTickerReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTickerReq) Reset()         { *m = GetTickerReq{} }
func (m *GetTickerReq) String() string { return proto.CompactTextString(m) }
func (*GetTickerReq) ProtoMessage()    {}
func (*GetTickerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{22}
}

func (m *GetTickerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTickerReq.Unmarshal(m, b)
}
func (m *GetTickerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTickerReq.Marshal(b, m, deterministic)
}
func (m *GetTickerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTickerReq.Merge(m, src)
}
func (m *GetTickerReq) XXX_Size() int {
	return xxx_messageInfo_GetTickerReq.Size(m)
}
func (m *GetTickerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTickerReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTickerReq proto.InternalMessageInfo

type GetTickerResponse struct {
	Data                 []byte   `protobuf:"bytes,7,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTickerResponse) Reset()         { *m = GetTickerResponse{} }
func (m *GetTickerResponse) String() string { return proto.CompactTextString(m) }
func (*GetTickerResponse) ProtoMessage()    {}
func (*GetTickerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ebaf8a149334f77, []int{23}
}

func (m *GetTickerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTickerResponse.Unmarshal(m, b)
}
func (m *GetTickerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTickerResponse.Marshal(b, m, deterministic)
}
func (m *GetTickerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTickerResponse.Merge(m, src)
}
func (m *GetTickerResponse) XXX_Size() int {
	return xxx_messageInfo_GetTickerResponse.Size(m)
}
func (m *GetTickerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTickerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTickerResponse proto.InternalMessageInfo

func (m *GetTickerResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*TriggerReq)(nil), "proto.TriggerReq")
	proto.RegisterType((*TriggerResponse)(nil), "proto.TriggerResponse")
	proto.RegisterType((*WorkerRespReq)(nil), "proto.WorkerRespReq")
	proto.RegisterType((*WorkerRespResponse)(nil), "proto.WorkerRespResponse")
	proto.RegisterType((*WorkerExceptionReq)(nil), "proto.WorkerExceptionReq")
	proto.RegisterType((*WorkerExceptionResponse)(nil), "proto.WorkerExceptionResponse")
	proto.RegisterType((*HookReq)(nil), "proto.HookReq")
	proto.RegisterType((*HookResponse)(nil), "proto.HookResponse")
	proto.RegisterType((*GetPlaybookReq)(nil), "proto.GetPlaybookReq")
	proto.RegisterType((*GetPlaybookResponse)(nil), "proto.GetPlaybookResponse")
	proto.RegisterType((*SwitchVersionReq)(nil), "proto.SwitchVersionReq")
	proto.RegisterType((*SwitchVersionResponse)(nil), "proto.SwitchVersionResponse")
	proto.RegisterType((*SubmitPlayBookReq)(nil), "proto.SubmitPlayBookReq")
	proto.RegisterType((*SubmitPlayBookResponse)(nil), "proto.SubmitPlayBookResponse")
	proto.RegisterType((*UpdateAppInternalReq)(nil), "proto.UpdateAppInternalReq")
	proto.RegisterType((*UpdateAppInternalResponse)(nil), "proto.UpdateAppInternalResponse")
	proto.RegisterType((*PingReq)(nil), "proto.PingReq")
	proto.RegisterType((*PongResponse)(nil), "proto.PongResponse")
	proto.RegisterType((*GetCacheReq)(nil), "proto.GetCacheReq")
	proto.RegisterType((*GetCacheResponse)(nil), "proto.GetCacheResponse")
	proto.RegisterType((*GetAckReq)(nil), "proto.GetAckReq")
	proto.RegisterType((*GetAckResponse)(nil), "proto.GetAckResponse")
	proto.RegisterType((*GetTickerReq)(nil), "proto.GetTickerReq")
	proto.RegisterType((*GetTickerResponse)(nil), "proto.GetTickerResponse")
}

func init() {
	proto.RegisterFile("component/service/proto/flow.proto", fileDescriptor_8ebaf8a149334f77)
}

var fileDescriptor_8ebaf8a149334f77 = []byte{
	// 869 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x0d, 0x1d, 0x3d, 0xec, 0x6b, 0x59, 0xb1, 0xc7, 0xb1, 0xcd, 0xb0, 0x6d, 0x20, 0x4c, 0x8b,
	0x54, 0x5d, 0xc4, 0x46, 0x1c, 0xa0, 0x0f, 0x34, 0x1b, 0xc9, 0x35, 0x5c, 0xa1, 0x88, 0x21, 0x8c,
	0xd4, 0x16, 0xe8, 0xa2, 0x00, 0x45, 0x4e, 0x6d, 0x42, 0x32, 0x67, 0x4c, 0x8e, 0x93, 0x6a, 0xdd,
	0x4d, 0xbf, 0xa6, 0x1f, 0xd0, 0x3f, 0xea, 0x5f, 0x14, 0xf3, 0x24, 0x45, 0x3d, 0x8a, 0x22, 0x2b,
	0xde, 0x7b, 0x78, 0xe7, 0xcc, 0xb9, 0x33, 0x73, 0x2e, 0xe0, 0x88, 0xdd, 0x71, 0x96, 0xd2, 0x54,
	0x9c, 0xe5, 0x34, 0x7b, 0x97, 0x44, 0xf4, 0x8c, 0x67, 0x4c, 0xb0, 0xb3, 0xdf, 0x66, 0xec, 0xfd,
	0xa9, 0x0a, 0x51, 0x5d, 0x7d, 0xf0, 0x5f, 0x1e, 0xc0, 0x38, 0x4b, 0x6e, 0x6e, 0x68, 0x46, 0xe8,
	0x3d, 0xda, 0x87, 0xc7, 0xa3, 0xec, 0x9d, 0xef, 0x75, 0xbc, 0xee, 0x0e, 0x91, 0xa1, 0x44, 0xde,
	0xb2, 0xd8, 0xdf, 0xea, 0x78, 0xdd, 0x3d, 0x22, 0x43, 0xe4, 0x43, 0xb3, 0xc7, 0xf9, 0x75, 0x78,
	0x47, 0xfd, 0xc7, 0xaa, 0xce, 0xa6, 0xe8, 0x39, 0xc0, 0x70, 0x16, 0xce, 0x27, 0x8c, 0x4d, 0x07,
	0xb1, 0x5f, 0xeb, 0x78, 0xdd, 0x3a, 0x29, 0x21, 0x28, 0x80, 0xed, 0x1e, 0xe7, 0x63, 0x36, 0xa5,
	0xa9, 0x5f, 0x57, 0x4b, 0x5d, 0x8e, 0x10, 0xd4, 0x46, 0xf3, 0x34, 0xf2, 0x1b, 0x1d, 0xaf, 0xbb,
	0x4d, 0x54, 0x2c, 0xb1, 0xef, 0x42, 0x11, 0xfa, 0xcd, 0x8e, 0xd7, 0x6d, 0x11, 0x15, 0xe3, 0x4b,
	0x78, 0xe2, 0xf4, 0xe6, 0x9c, 0xa5, 0x39, 0x75, 0x65, 0x5a, 0xb5, 0x8a, 0xa5, 0x14, 0x49, 0x41,
	0x68, 0xfe, 0x30, 0x13, 0x4a, 0x7d, 0x8b, 0x94, 0x10, 0xfc, 0x16, 0xf6, 0x7e, 0x66, 0xd9, 0x54,
	0xb3, 0xfc, 0x8f, 0xce, 0x87, 0xe1, 0x7c, 0xc6, 0xc2, 0x58, 0x75, 0xde, 0x22, 0x36, 0xc5, 0x5d,
	0x40, 0x65, 0xba, 0xf5, 0xc2, 0x30, 0xb1, 0x95, 0x97, 0xbf, 0x47, 0x94, 0x8b, 0x84, 0xa5, 0x1f,
	0xbe, 0xfb, 0x4b, 0x38, 0x59, 0xe2, 0xdc, 0x20, 0xe1, 0x0f, 0x0f, 0x9a, 0xdf, 0x33, 0x36, 0x95,
	0x1b, 0xfb, 0xd0, 0x1c, 0x67, 0x61, 0x44, 0x07, 0xb1, 0x2a, 0xa9, 0x11, 0x9b, 0xca, 0xcb, 0xba,
	0x66, 0x31, 0xbd, 0x60, 0x31, 0x55, 0x2a, 0x76, 0x88, 0xcb, 0xd5, 0xe9, 0xa6, 0x21, 0xcf, 0x6f,
	0x99, 0x18, 0x68, 0x35, 0x7b, 0xa4, 0x84, 0xd8, 0x76, 0x6a, 0x4b, 0xed, 0xd4, 0x5d, 0x3b, 0x18,
	0x43, 0x4b, 0x8b, 0xd8, 0xa0, 0xf4, 0x33, 0x68, 0x5f, 0x51, 0x61, 0x5f, 0x90, 0xd4, 0x8b, 0xa0,
	0x36, 0x9c, 0x24, 0x5a, 0x6c, 0x9d, 0xa8, 0x18, 0x7f, 0x01, 0x87, 0x0b, 0x55, 0x2b, 0x08, 0x5b,
	0xee, 0xf4, 0xf7, 0x47, 0xef, 0x13, 0x11, 0xdd, 0xfe, 0x44, 0xb3, 0xdc, 0x9c, 0xbd, 0x79, 0xb5,
	0x7d, 0xfd, 0x6a, 0xbd, 0xe2, 0xd5, 0x6a, 0xc4, 0x36, 0x3b, 0xd2, 0xcd, 0x6e, 0xe9, 0xff, 0x05,
	0x82, 0xbf, 0x82, 0xa3, 0x0a, 0xa7, 0x11, 0xf0, 0x1f, 0xc4, 0xf8, 0x73, 0x38, 0x18, 0x3d, 0x4c,
	0xee, 0x12, 0x61, 0x31, 0xd3, 0x60, 0x9f, 0xc5, 0x73, 0xab, 0x5a, 0xc6, 0xf8, 0x6b, 0x38, 0xae,
	0x16, 0x2e, 0x6e, 0x31, 0x59, 0xda, 0x42, 0x23, 0x98, 0xc3, 0xd3, 0x1f, 0x79, 0x1c, 0x0a, 0xda,
	0xe3, 0x7c, 0x90, 0x0a, 0x9a, 0xa5, 0xe1, 0x4c, 0xee, 0x72, 0x0c, 0x8d, 0x91, 0x08, 0xc5, 0x43,
	0x6e, 0x8e, 0xdb, 0x64, 0xe8, 0x29, 0xd4, 0x65, 0xa5, 0x6d, 0x53, 0x27, 0xf2, 0x91, 0xf4, 0x33,
	0x36, 0xa5, 0x59, 0x6e, 0x1d, 0x6f, 0x52, 0x79, 0xad, 0x97, 0x3c, 0x37, 0x56, 0x97, 0x21, 0x7e,
	0x05, 0xcf, 0x56, 0xec, 0x68, 0xe4, 0x3a, 0x7a, 0xaf, 0x44, 0x8f, 0x3f, 0x85, 0xe6, 0x30, 0x49,
	0x6f, 0xcc, 0x73, 0xbc, 0xa3, 0x79, 0x1e, 0xde, 0x50, 0x23, 0xcc, 0xa6, 0xf8, 0x05, 0xb4, 0x86,
	0x4c, 0x16, 0x19, 0xaa, 0x63, 0x68, 0xe4, 0x45, 0x07, 0x75, 0x62, 0x32, 0xbc, 0x07, 0xbb, 0x57,
	0x54, 0x5c, 0x84, 0xd1, 0x2d, 0x25, 0xf4, 0x1e, 0xbf, 0x80, 0xfd, 0x22, 0xdd, 0xf0, 0x30, 0x76,
	0x61, 0xe7, 0x8a, 0x8a, 0x5e, 0x24, 0xef, 0xc0, 0x3c, 0x3b, 0x95, 0x6c, 0x58, 0xd2, 0x86, 0xd6,
	0x15, 0x15, 0xe3, 0x24, 0x52, 0xb6, 0xbf, 0x97, 0xd7, 0x59, 0xca, 0x2b, 0x0b, 0x4b, 0x23, 0xec,
	0xfc, 0xcf, 0xad, 0x62, 0xe6, 0xf2, 0x08, 0x7d, 0x29, 0x2d, 0xa8, 0x32, 0x74, 0xa0, 0x87, 0xf3,
	0x69, 0x31, 0x91, 0x83, 0xe3, 0x2a, 0xa4, 0x89, 0xf1, 0x23, 0x74, 0x01, 0xed, 0x62, 0xe6, 0xe8,
	0xe3, 0x35, 0xb5, 0x0b, 0x93, 0x2d, 0x78, 0xb6, 0x02, 0x75, 0x24, 0xd7, 0xf0, 0xa4, 0x32, 0x3a,
	0xd0, 0x62, 0x7d, 0x79, 0x4c, 0x05, 0xcf, 0xd7, 0xfd, 0x72, 0x7c, 0x2f, 0xa1, 0x26, 0x5d, 0x8d,
	0xda, 0xa6, 0xd2, 0xcc, 0x99, 0xe0, 0x70, 0x21, 0xb7, 0xe5, 0xe7, 0xff, 0x78, 0xb0, 0xeb, 0x8c,
	0xcb, 0x23, 0xd4, 0x57, 0xb7, 0x67, 0x11, 0x74, 0x64, 0x56, 0x2d, 0x0e, 0x81, 0x20, 0x58, 0x05,
	0x3b, 0x09, 0x03, 0x68, 0x6b, 0x3f, 0xda, 0x81, 0x84, 0x4e, 0x4c, 0x7d, 0xd5, 0xfa, 0xc1, 0xc7,
	0xab, 0x7f, 0x38, 0xaa, 0x1f, 0xa0, 0xbd, 0x68, 0x3c, 0xe4, 0xdb, 0x15, 0x55, 0xe3, 0x06, 0x9f,
	0xac, 0xf9, 0xe3, 0x7a, 0xfd, 0x15, 0x1a, 0x3d, 0xce, 0x65, 0x97, 0x63, 0x38, 0x58, 0xf2, 0x08,
	0xfa, 0xc8, 0xac, 0x5f, 0xe5, 0xd7, 0xa0, 0xb3, 0xfe, 0xa7, 0xe3, 0x7f, 0x63, 0x6c, 0xc4, 0x23,
	0xf4, 0x0a, 0xb6, 0x65, 0x38, 0xa6, 0xb9, 0x70, 0x37, 0x61, 0x2c, 0xe6, 0x6e, 0xa2, 0xec, 0x26,
	0xfc, 0xe8, 0xfc, 0x6f, 0x0f, 0xe0, 0x82, 0xa5, 0x39, 0x9b, 0x51, 0xc9, 0xf0, 0x0d, 0x6c, 0x5b,
	0xdf, 0x20, 0x54, 0x1c, 0xb7, 0xf5, 0x55, 0x70, 0xb2, 0x84, 0xb9, 0x43, 0x7b, 0x0d, 0x0d, 0xed,
	0x1e, 0xb4, 0x5f, 0x14, 0x69, 0x67, 0x05, 0x47, 0x15, 0xc4, 0x2d, 0x7a, 0xa3, 0xfc, 0xa7, 0xcd,
	0x83, 0x0e, 0x8b, 0x2a, 0x67, 0xaf, 0xc0, 0x5f, 0x06, 0xed, 0xea, 0xfe, 0xce, 0x2f, 0xcd, 0xd3,
	0x6f, 0xd5, 0xef, 0x49, 0x43, 0x7d, 0x5e, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xee, 0x83, 0x23,
	0x63, 0x04, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TriggerRpcClient is the client API for TriggerRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TriggerRpcClient interface {
	Trigger(ctx context.Context, in *TriggerReq, opts ...grpc.CallOption) (*TriggerResponse, error)
	WorkerResponse(ctx context.Context, in *WorkerRespReq, opts ...grpc.CallOption) (*WorkerRespResponse, error)
	WorkerException(ctx context.Context, in *WorkerExceptionReq, opts ...grpc.CallOption) (*WorkerExceptionResponse, error)
	Hook(ctx context.Context, in *HookReq, opts ...grpc.CallOption) (*HookResponse, error)
}

type triggerRpcClient struct {
	cc *grpc.ClientConn
}

func NewTriggerRpcClient(cc *grpc.ClientConn) TriggerRpcClient {
	return &triggerRpcClient{cc}
}

func (c *triggerRpcClient) Trigger(ctx context.Context, in *TriggerReq, opts ...grpc.CallOption) (*TriggerResponse, error) {
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, "/proto.TriggerRpc/Trigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *triggerRpcClient) WorkerResponse(ctx context.Context, in *WorkerRespReq, opts ...grpc.CallOption) (*WorkerRespResponse, error) {
	out := new(WorkerRespResponse)
	err := c.cc.Invoke(ctx, "/proto.TriggerRpc/WorkerResponse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *triggerRpcClient) WorkerException(ctx context.Context, in *WorkerExceptionReq, opts ...grpc.CallOption) (*WorkerExceptionResponse, error) {
	out := new(WorkerExceptionResponse)
	err := c.cc.Invoke(ctx, "/proto.TriggerRpc/WorkerException", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *triggerRpcClient) Hook(ctx context.Context, in *HookReq, opts ...grpc.CallOption) (*HookResponse, error) {
	out := new(HookResponse)
	err := c.cc.Invoke(ctx, "/proto.TriggerRpc/Hook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TriggerRpcServer is the server API for TriggerRpc service.
type TriggerRpcServer interface {
	Trigger(context.Context, *TriggerReq) (*TriggerResponse, error)
	WorkerResponse(context.Context, *WorkerRespReq) (*WorkerRespResponse, error)
	WorkerException(context.Context, *WorkerExceptionReq) (*WorkerExceptionResponse, error)
	Hook(context.Context, *HookReq) (*HookResponse, error)
}

// UnimplementedTriggerRpcServer can be embedded to have forward compatible implementations.
type UnimplementedTriggerRpcServer struct {
}

func (*UnimplementedTriggerRpcServer) Trigger(ctx context.Context, req *TriggerReq) (*TriggerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trigger not implemented")
}
func (*UnimplementedTriggerRpcServer) WorkerResponse(ctx context.Context, req *WorkerRespReq) (*WorkerRespResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkerResponse not implemented")
}
func (*UnimplementedTriggerRpcServer) WorkerException(ctx context.Context, req *WorkerExceptionReq) (*WorkerExceptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkerException not implemented")
}
func (*UnimplementedTriggerRpcServer) Hook(ctx context.Context, req *HookReq) (*HookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hook not implemented")
}

func RegisterTriggerRpcServer(s *grpc.Server, srv TriggerRpcServer) {
	s.RegisterService(&_TriggerRpc_serviceDesc, srv)
}

func _TriggerRpc_Trigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerRpcServer).Trigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TriggerRpc/Trigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerRpcServer).Trigger(ctx, req.(*TriggerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TriggerRpc_WorkerResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerRespReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerRpcServer).WorkerResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TriggerRpc/WorkerResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerRpcServer).WorkerResponse(ctx, req.(*WorkerRespReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TriggerRpc_WorkerException_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerExceptionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerRpcServer).WorkerException(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TriggerRpc/WorkerException",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerRpcServer).WorkerException(ctx, req.(*WorkerExceptionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TriggerRpc_Hook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerRpcServer).Hook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TriggerRpc/Hook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerRpcServer).Hook(ctx, req.(*HookReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _TriggerRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TriggerRpc",
	HandlerType: (*TriggerRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Trigger",
			Handler:    _TriggerRpc_Trigger_Handler,
		},
		{
			MethodName: "WorkerResponse",
			Handler:    _TriggerRpc_WorkerResponse_Handler,
		},
		{
			MethodName: "WorkerException",
			Handler:    _TriggerRpc_WorkerException_Handler,
		},
		{
			MethodName: "Hook",
			Handler:    _TriggerRpc_Hook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "component/service/proto/flow.proto",
}

// PlaybookRpcClient is the client API for PlaybookRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlaybookRpcClient interface {
	GetPlaybook(ctx context.Context, in *GetPlaybookReq, opts ...grpc.CallOption) (*GetPlaybookResponse, error)
	SwitchSnapshot(ctx context.Context, in *SwitchVersionReq, opts ...grpc.CallOption) (*SwitchVersionResponse, error)
	SubmitPlayBook(ctx context.Context, in *SubmitPlayBookReq, opts ...grpc.CallOption) (*SubmitPlayBookResponse, error)
}

type playbookRpcClient struct {
	cc *grpc.ClientConn
}

func NewPlaybookRpcClient(cc *grpc.ClientConn) PlaybookRpcClient {
	return &playbookRpcClient{cc}
}

func (c *playbookRpcClient) GetPlaybook(ctx context.Context, in *GetPlaybookReq, opts ...grpc.CallOption) (*GetPlaybookResponse, error) {
	out := new(GetPlaybookResponse)
	err := c.cc.Invoke(ctx, "/proto.PlaybookRpc/GetPlaybook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbookRpcClient) SwitchSnapshot(ctx context.Context, in *SwitchVersionReq, opts ...grpc.CallOption) (*SwitchVersionResponse, error) {
	out := new(SwitchVersionResponse)
	err := c.cc.Invoke(ctx, "/proto.PlaybookRpc/SwitchSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbookRpcClient) SubmitPlayBook(ctx context.Context, in *SubmitPlayBookReq, opts ...grpc.CallOption) (*SubmitPlayBookResponse, error) {
	out := new(SubmitPlayBookResponse)
	err := c.cc.Invoke(ctx, "/proto.PlaybookRpc/SubmitPlayBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaybookRpcServer is the server API for PlaybookRpc service.
type PlaybookRpcServer interface {
	GetPlaybook(context.Context, *GetPlaybookReq) (*GetPlaybookResponse, error)
	SwitchSnapshot(context.Context, *SwitchVersionReq) (*SwitchVersionResponse, error)
	SubmitPlayBook(context.Context, *SubmitPlayBookReq) (*SubmitPlayBookResponse, error)
}

// UnimplementedPlaybookRpcServer can be embedded to have forward compatible implementations.
type UnimplementedPlaybookRpcServer struct {
}

func (*UnimplementedPlaybookRpcServer) GetPlaybook(ctx context.Context, req *GetPlaybookReq) (*GetPlaybookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaybook not implemented")
}
func (*UnimplementedPlaybookRpcServer) SwitchSnapshot(ctx context.Context, req *SwitchVersionReq) (*SwitchVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwitchSnapshot not implemented")
}
func (*UnimplementedPlaybookRpcServer) SubmitPlayBook(ctx context.Context, req *SubmitPlayBookReq) (*SubmitPlayBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPlayBook not implemented")
}

func RegisterPlaybookRpcServer(s *grpc.Server, srv PlaybookRpcServer) {
	s.RegisterService(&_PlaybookRpc_serviceDesc, srv)
}

func _PlaybookRpc_GetPlaybook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaybookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybookRpcServer).GetPlaybook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PlaybookRpc/GetPlaybook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybookRpcServer).GetPlaybook(ctx, req.(*GetPlaybookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybookRpc_SwitchSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchVersionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybookRpcServer).SwitchSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PlaybookRpc/SwitchSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybookRpcServer).SwitchSnapshot(ctx, req.(*SwitchVersionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybookRpc_SubmitPlayBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPlayBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybookRpcServer).SubmitPlayBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PlaybookRpc/SubmitPlayBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybookRpcServer).SubmitPlayBook(ctx, req.(*SubmitPlayBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlaybookRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PlaybookRpc",
	HandlerType: (*PlaybookRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlaybook",
			Handler:    _PlaybookRpc_GetPlaybook_Handler,
		},
		{
			MethodName: "SwitchSnapshot",
			Handler:    _PlaybookRpc_SwitchSnapshot_Handler,
		},
		{
			MethodName: "SubmitPlayBook",
			Handler:    _PlaybookRpc_SubmitPlayBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "component/service/proto/flow.proto",
}

// AppRpcClient is the client API for AppRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppRpcClient interface {
	UpdateAppInternal(ctx context.Context, in *UpdateAppInternalReq, opts ...grpc.CallOption) (*UpdateAppInternalResponse, error)
}

type appRpcClient struct {
	cc *grpc.ClientConn
}

func NewAppRpcClient(cc *grpc.ClientConn) AppRpcClient {
	return &appRpcClient{cc}
}

func (c *appRpcClient) UpdateAppInternal(ctx context.Context, in *UpdateAppInternalReq, opts ...grpc.CallOption) (*UpdateAppInternalResponse, error) {
	out := new(UpdateAppInternalResponse)
	err := c.cc.Invoke(ctx, "/proto.AppRpc/UpdateAppInternal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppRpcServer is the server API for AppRpc service.
type AppRpcServer interface {
	UpdateAppInternal(context.Context, *UpdateAppInternalReq) (*UpdateAppInternalResponse, error)
}

// UnimplementedAppRpcServer can be embedded to have forward compatible implementations.
type UnimplementedAppRpcServer struct {
}

func (*UnimplementedAppRpcServer) UpdateAppInternal(ctx context.Context, req *UpdateAppInternalReq) (*UpdateAppInternalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAppInternal not implemented")
}

func RegisterAppRpcServer(s *grpc.Server, srv AppRpcServer) {
	s.RegisterService(&_AppRpc_serviceDesc, srv)
}

func _AppRpc_UpdateAppInternal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAppInternalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRpcServer).UpdateAppInternal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AppRpc/UpdateAppInternal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRpcServer).UpdateAppInternal(ctx, req.(*UpdateAppInternalReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AppRpc",
	HandlerType: (*AppRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateAppInternal",
			Handler:    _AppRpc_UpdateAppInternal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "component/service/proto/flow.proto",
}

// PingRpcClient is the client API for PingRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingRpcClient interface {
	PingTest(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PongResponse, error)
}

type pingRpcClient struct {
	cc *grpc.ClientConn
}

func NewPingRpcClient(cc *grpc.ClientConn) PingRpcClient {
	return &pingRpcClient{cc}
}

func (c *pingRpcClient) PingTest(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PongResponse, error) {
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, "/proto.PingRpc/PingTest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingRpcServer is the server API for PingRpc service.
type PingRpcServer interface {
	PingTest(context.Context, *PingReq) (*PongResponse, error)
}

// UnimplementedPingRpcServer can be embedded to have forward compatible implementations.
type UnimplementedPingRpcServer struct {
}

func (*UnimplementedPingRpcServer) PingTest(ctx context.Context, req *PingReq) (*PongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingTest not implemented")
}

func RegisterPingRpcServer(s *grpc.Server, srv PingRpcServer) {
	s.RegisterService(&_PingRpc_serviceDesc, srv)
}

func _PingRpc_PingTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingRpcServer).PingTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PingRpc/PingTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingRpcServer).PingTest(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PingRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PingRpc",
	HandlerType: (*PingRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingTest",
			Handler:    _PingRpc_PingTest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "component/service/proto/flow.proto",
}

// ConsoleRpcClient is the client API for ConsoleRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConsoleRpcClient interface {
	GetCache(ctx context.Context, in *GetCacheReq, opts ...grpc.CallOption) (*GetCacheResponse, error)
	GetAck(ctx context.Context, in *GetAckReq, opts ...grpc.CallOption) (*GetAckResponse, error)
	GetTicker(ctx context.Context, in *GetTickerReq, opts ...grpc.CallOption) (*GetTickerResponse, error)
}

type consoleRpcClient struct {
	cc *grpc.ClientConn
}

func NewConsoleRpcClient(cc *grpc.ClientConn) ConsoleRpcClient {
	return &consoleRpcClient{cc}
}

func (c *consoleRpcClient) GetCache(ctx context.Context, in *GetCacheReq, opts ...grpc.CallOption) (*GetCacheResponse, error) {
	out := new(GetCacheResponse)
	err := c.cc.Invoke(ctx, "/proto.ConsoleRpc/GetCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleRpcClient) GetAck(ctx context.Context, in *GetAckReq, opts ...grpc.CallOption) (*GetAckResponse, error) {
	out := new(GetAckResponse)
	err := c.cc.Invoke(ctx, "/proto.ConsoleRpc/GetAck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consoleRpcClient) GetTicker(ctx context.Context, in *GetTickerReq, opts ...grpc.CallOption) (*GetTickerResponse, error) {
	out := new(GetTickerResponse)
	err := c.cc.Invoke(ctx, "/proto.ConsoleRpc/GetTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsoleRpcServer is the server API for ConsoleRpc service.
type ConsoleRpcServer interface {
	GetCache(context.Context, *GetCacheReq) (*GetCacheResponse, error)
	GetAck(context.Context, *GetAckReq) (*GetAckResponse, error)
	GetTicker(context.Context, *GetTickerReq) (*GetTickerResponse, error)
}

// UnimplementedConsoleRpcServer can be embedded to have forward compatible implementations.
type UnimplementedConsoleRpcServer struct {
}

func (*UnimplementedConsoleRpcServer) GetCache(ctx context.Context, req *GetCacheReq) (*GetCacheResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCache not implemented")
}
func (*UnimplementedConsoleRpcServer) GetAck(ctx context.Context, req *GetAckReq) (*GetAckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAck not implemented")
}
func (*UnimplementedConsoleRpcServer) GetTicker(ctx context.Context, req *GetTickerReq) (*GetTickerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTicker not implemented")
}

func RegisterConsoleRpcServer(s *grpc.Server, srv ConsoleRpcServer) {
	s.RegisterService(&_ConsoleRpc_serviceDesc, srv)
}

func _ConsoleRpc_GetCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCacheReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleRpcServer).GetCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ConsoleRpc/GetCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleRpcServer).GetCache(ctx, req.(*GetCacheReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleRpc_GetAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleRpcServer).GetAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ConsoleRpc/GetAck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleRpcServer).GetAck(ctx, req.(*GetAckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsoleRpc_GetTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTickerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsoleRpcServer).GetTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ConsoleRpc/GetTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsoleRpcServer).GetTicker(ctx, req.(*GetTickerReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConsoleRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ConsoleRpc",
	HandlerType: (*ConsoleRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCache",
			Handler:    _ConsoleRpc_GetCache_Handler,
		},
		{
			MethodName: "GetAck",
			Handler:    _ConsoleRpc_GetAck_Handler,
		},
		{
			MethodName: "GetTicker",
			Handler:    _ConsoleRpc_GetTicker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "component/service/proto/flow.proto",
}
