{
 "title": "魔方编排监控",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "触发任务QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flow_tag{tag=\"Trigger\"}"
    }
   ]
  },
  {
   "title": "已完成任务QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "flow_tag{tag=\"Complied\"}"
    }
   ]
  },
  {
   "title": "内存同步channel信号数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sync_count{}" }
   ]
  },
  {
   "title": "内存trace记录数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 8 },
   "targets": [
    { "expr": "trace_count{}" }
   ]
  },
  {
   "title": "暂未完成任务数（时间短下pod数量如下）",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "residual_task_count{}" }
   ]
  },
  {
   "title": "worker返回错误记录",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "flow_tag{tag=\"WorkerException\"}"
    }
   ]
  },
  {
   "title": "调度引擎内部异常",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "flow_tag{tag=\"ServerException\"}"
    }
   ]
  },
  {
   "title": "配置中心-APP变更",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "flow_tag{tag=\"AppPut\"}"
    }
   ]
  },
  {
   "title": "配置中心-剧本创建/切换",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "flow_tag{tag=\"PlaybookPut\"}"
    }
   ]
  }
 ]
}